name: Cron Job

on:
  schedule: # 00:00 JST == 15:00 UTC
    - cron: "0 7 * * *"
    - cron: "0 15 * * *"
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: ${{ secrets.DB_SECRET }}
          path: "backup.sql" 
          options: "-O -N supabase_functions"
          
      - name: Pushes Dumped Backup
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'backup.sql'
          destination_repo: 'fkunn1326/pg-backup'
          destination_folder: 'backups'
          user_email: 'github-actions@github.com'
          user_name: 'github-actions'
          commit_message: 'Backup!'
